server:
  port: 8001
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      cookie:
        domain:
        same-site: LAX
        secure: true


spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-1.cpu0oqm8wdha.ap-northeast-2.rds.amazonaws.com:3306/baekjunghyun?serverTimezone=Asia/Seoul
    username: admin
    password: admin2580!
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      #use-new-id-generator-mappings: false
    show-sql: true
    properties:
      "[hibernateformat_sql]": true

  jackson:
    serialization:
      fail-on-empty-beans: false

  cloud:
    aws:
      region:
        static: ap-northeast-2

  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB
        
